version: '3.1'

volumes:
  pg_docker:

services:
  docker_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=docker_db
    volumes:
      - pg_docker:/var/lib/postgresql/data
    ports:
      - "5433:5432"

